trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo azure-k8s-with-Terraform!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'id_rsa.pub'

- task: TerraformInstaller@0
  name update-terraform
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    secureVarsFile: '''-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'''
    commandOptions: 'init'
    allowTelemetryCollection: true