version: '3.1'
services:
  springboot:
    image: J-Babi/springbootmongo-docker:1
    restart: always # This will be ignored if we deploy in docker swarm
    ports:
      - 800:8080
    networks:
      -boa
networks:
  boa: 
