trigger:
- main

# strategy:
#   matrix:
#     linux:
#       operatingSystem: ubuntu-latest
#     windows: 
#       operatingSystem: windows-latest

pool:
  vmImage: ubuntu-latest

stages: 
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Doing the build"

- stage: DevDeploy
  dependsOn: Build
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy builds to Dev

- stage: QADeploy
  dependsOn: Build
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to QA

- stage: ProdDeploy
  dependsOn: 
  - QADeploy 
  jobs:
  - deployment: ProdDeployJob
    environment: Prod
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to Prod


